name: python-data
dependencies:
- appnope=0.1.0=py34_0
- backports=1.0=py34_0
- backports.shutil_get_terminal_size=1.0.0=py_3
- backports_abc=0.5=py34_0
- blas=1.1=openblas
- bokeh=0.11.1=py34_0
- ca-certificates=2016.2.28=0
- cloudpickle=0.2.1=py34_2
- configparser=3.5.0=py34_0
- cycler=0.10.0=py34_0
- dask=0.9.0=py34_2
- decorator=4.0.9=py34_0
- entrypoints=0.2.1=py34_0
- freetype=2.6.3=1
- get_terminal_size=1.0.0=py34_0
- ipykernel=4.3.1=py34_1
- ipython=4.2.0=py34_0
- ipython_genutils=0.1.0=py34_0
- ipywidgets=5.1.5=py34_0
- jinja2=2.8.1=py34_0
- jsonschema=2.5.1=py34_0
- jupyter_client=4.2.2=py34_0
- jupyter_core=4.1.0=py34_0
- libgfortran=3.0.0=1
- libpng=1.6.21=1
- locket=0.2.0=py34_1
- markupsafe=0.23=py34_2
- matplotlib=1.5.1=np111py34_3
- mistune=0.7.2=py34_1
- mkl=11.3.3=0
- nbconvert=4.2.0=py34_0
- nbformat=4.0.1=py34_0
- notebook=4.2.0=py34_0
- numpy=1.11.0=py34_blas_openblas_201
- openblas=0.2.18=6
- openssl=1.0.2h=3
- pandas=0.18.1=np111py34_1
- partd=0.3.3=py34_0
- pexpect=4.1.0=py34_0
- pickleshare=0.7.2=py34_0
- pip=8.1.1=py34_1
- ptyprocess=0.5.1=py34_0
- pygments=2.1.3=py34_1
- pyparsing=2.1.4=py34_0
- python=3.4.4=0
- python-dateutil=2.5.3=py34_0
- python.app=1.2=py34_4
- pytz=2016.4=py34_0
- pyyaml=3.11=py34_4
- pyzmq=15.2.0=py34_1
- readline=6.2=2
- requests=2.10.0=py34_0
- scikit-learn=0.17.1=np111py34_blas_openblas_202
- scipy=0.17.1=np111py34_blas_openblas_204
- seaborn=0.7.0=py34_0
- setuptools=21.2.1=py34_0
- simplegeneric=0.8.1=py34_1
- six=1.10.0=py34_1
- sqlite=3.9.2=0
- terminado=0.6=py34_0
- tk=8.5.19=2
- toolz=0.7.4=py34_0
- tornado=4.3=py34_1
- traitlets=4.2.1=py34_0
- wheel=0.29.0=py34_0
- widgetsnbextension=1.2.3=py34_1
- xz=5.0.5=1
- yaml=0.1.6=0
- zlib=1.2.8=3
- pip:
  - backports-abc==0.5
  - backports.shutil-get-terminal-size==1.0.0
  - ipython-genutils==0.1.0
  - jupyter-client==4.2.2
  - jupyter-core==4.1.0

